// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const listPatients = `-- name: ListPatients :many
SELECT id, name, psychologist_id, email, phone, created_at FROM patients
WHERE psychologist_id = ?
`

func (q *Queries) ListPatients(ctx context.Context, psychologistID int64) ([]Patient, error) {
	rows, err := q.db.QueryContext(ctx, listPatients, psychologistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PsychologistID,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
